### PR TITLE
Update chocolateyInstall.ps1

### PR DESCRIPTION
**Pull request by tirolo**
As the package failed the automated package test (https://gist.github.com/choco-bot/23a151445d7005d40f31) I've updated script with suggested validation against system requirements.

### CODE REVIEW

**Comment by tirolo** [comment]
Removed the .net version check.

On the website they say:
It will run on: Windows 2000, Windows XP, Windows Server 2003, Windows Vista, or Windows 7. 
It will not run on: Windows 95, Windows 98, Windows ME, or Windows NT 4.

Nothing explicit about other versions (maybe because it was published on jan/2007?). I thought that implementing an OS version check for only the ones it explicitly state as supported would be a nice place to start.

The goal was to get the package passing the automated tests, is there any suggestion on how we can achieve that?

**Comment by aronovgj** [comment]
Well, if the goal is passing the tests then we can exclude Windows Server 2012 x64. And every time someone complains that it doesn't work on his OS we can update the script and exclude it. I just don't want to exclude people from using a package if this actually might work on an OS.

**Comment by tirolo** [comment]
Looking from that point of view makes perfect sense for me. Already changed the script to exclude windows 2012 r2 only. (Haven't got a chance to test the package yet though, did edit through Github)

**Comment by tirolo** [comment]
Just tested the package seems to be working fine, would you like to suggest further changes?

**Comment by aronovgj** [comment]
I think I see a major conflict. In order to pass the validation the package has to install successfully. Thats what the package currently would do if I'm seeing it right. So no software will be installed but the package will. 
However, the package installation should fail if it is installed on Windows Server 2012. I'm not sure how do deal with this...

**Comment by aronovgj** [comment]
https://gitter.im/chocolatey/chocolatey.org?at=565c9364f0893e5f6b7293a9

**Comment by tirolo** [comment]
OMG how did I miss that... I should "throw" instead... Will amend that as
soon as I hit home....

**Comment by tirolo** [comment]
Forgot to update here. I did the changes to fail the package when trying to install on an unsupported OS. Also tested the package locally and seems to be working fine.

**Comment by aronovgj** [comment]
Good. Will try it myself and then merge and push. Thanks.

**Comment by aronovgj** [comment]
New version pushed

**Comment by aronovgj** [comment]
https://gist.github.com/choco-bot/23a151445d7005d40f31
Failed because validator got the old install script. That cache problem again, I guess...

**Comment by aronovgj** [comment]
https://gist.github.com/choco-bot/7e7a7a22c199a03b9744
Still fails. Ideas?  @tirolo

**Comment by aronovgj** [comment]
https://gist.github.com/choco-bot/e4948c2c225826a55701
Now you also can see debug messages. 

`==> default:  DEBUG: Current OS Version: 6.3.9600.0`
`==> default:  DEBUG: Current OS Name: Microsoft Windows Server 2012 R2 Datacenter`

**Pull request merged**
